# Generated by Django 6.0.7 on 2026-07-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='submission',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
