from django.urls import path
from .views import *

urlpatterns=[ # as_view converts the class based view into a callable function that django uses it in the path
    path('',Login.as_view(),name='login'),
    path('register/',Register.as_view(),name='register'),
    path('teacherdashboard/',TeacherDashBoard.as_view(),name='TeacherDashBoard'),
    path('createcourse/',CreateCourse.as_view(),name='CreateCourse'),
    path('createlesson/',CreateLesson.as_view(),name='CreateLesson'),
    path('createassignment/',CreateAssignment.as_view(),name='CreateAssignment'),
    path('createquiz/',CreateQuiz.as_view(),name='CreateQuiz'),
    
    path('createquestion/',CreateQuestion.as_view(),name='CreateQuestion'),
    path('createoption/',CreateOPtion.as_view(),name='CreateOPtion'),
    path('createannouncement/',CreateAnnouncement.as_view(),name='CreateAnnouncement'),
    
    path('studentdashboard/',StudentDashBoard.as_view(),name='StudentDashBoard'),
    path('lesson_list/',ViewLesson.as_view(),name='ViewLesson'),
    path('submitassignment/',SubmitAssignment.as_view(),name='SubmitAssignment'),
    path('viewquiz/',ViewQuiz.as_view(),name='ViewQuiz'),
    path('attemptquiz/<int:pk>/',AttemptQuiz.as_view(),name='AttemptQuiz'),
    
    path('coursedetail/<int:pk>/',CourseDetail.as_view(),name='CourseDetail'),
    path('createenrollment/',CreateEnrollement.as_view(),name='CreateEnrollement'),
    path('viewresult/',ViewResult.as_view(),name='ViewResult'),
    path('updatecourse/<int:pk>/',UpdateCourse.as_view(),name='UpdateCourse'),
    path('deletecourse/<int:pk>/',DeleteCourse.as_view(),name='DeleteCourse'),
    path('updateassignment/<int:pk>/',UpdateAssignment.as_view(),name='UpdateAssignment'),
    path('deleteassignment/<int:pk>/',DeleteAssignment.as_view(),name='DeleteAssignment'),
    path('deletelesson/<int:pk>/',DeleteLesson.as_view(),name='DeleteLesson'),
    path('updatelesson/<int:pk>/',UpdateLesson.as_view(),name='UpdateLesson'),
    path('deletequiz/<int:pk>/',DeleteQuiz.as_view(),name='DeleteQuiz'),
    path('updatequiz/<int:pk>/',UpdateQuiz.as_view(),name='UpdateQuiz'),
    path('deleteannouncement/<int:pk>/',DeleteAnnouncement.as_view(),name='DeleteAnnouncement'),
    path('updateannouncement/<int:pk>/',UpdateAnnouncement.as_view(),name='UpdateAnnouncement'),
    path('logout/', Logout.as_view(), name='logout'),
    path('viewresult/',ViewResult.as_view(),name='ViewResult'),
    path('createprogress/', TeacherProgress.as_view(), name='Progress'),
    path('viewprogress/', ViewProgress.as_view(), name='ViewProgress'),
    path('course/api/<int:pk>/',CourseAPI.as_view(),name='CourseAPIs'),
    path('course/api/',CourseAPI.as_view(),name='CourseAPIs'),
    path('lesson/api/<int:pk>/',LessonAPI.as_view(),name='LessonAPI'),
    path('lesson/api/',LessonAPI.as_view(),name='LessonAPI'),
    path('assignment/api/<int:pk>/',AssignmentAPI.as_view(),name='AssignmentAPI'),
     path('assignment/api/',AssignmentAPI.as_view(),name='AssignmentAPI'),
    path('quiz/api/<int:pk>/',QuizAPI.as_view(),name='QuizAPI'),
    path('quiz/api/',QuizAPI.as_view(),name='QuizAPI'),
    path('question/api/<int:pk>/',QuestionAPI.as_view(),name='QuestionAPI'),
    path('question/api/',QuestionAPI.as_view(),name='QuestionAPI'),
    path('option/api/<int:pk>/',OptionAPI.as_view(),name='OptionAPI'),
    path('option/api/',OptionAPI.as_view(),name='OptionAPI'),
    path('enrollment/api/<int:pk>/',EnrollmentAPI.as_view(),name='EnrollmentAPI'),
    path('enrollment/api/',EnrollmentAPI.as_view(),name='EnrollmentAPI'),
    path('result/api/<int:pk>/',ResultAPI.as_view(),name='ResultAPI'),
    path('result/api/',ResultAPI.as_view(),name='ResultAPI'),
    path('progress/api/<int:pk>/',ProgressAPI.as_view(),name='ProgressAPI'),
    path('progress/api/',ProgressAPI.as_view(),name='ProgressAPI'),
    path('givemarks/api/<int:pk>/', GiveMarks.as_view(), name='GiveMarks'),
path('studentsubmission/', StudentSubmission.as_view(), name='StudentSubmission'),
path('viewsubmission/',ViewSubmission.as_view(),name='ViewSubmission'),
path('assistant/',assistant,name='assistant'),
path('coursedet/<int:pk>/',CourseDetailStudent.as_view(),name='CourseDetailStudent')
] # we do not use as_view for a function based view